name: Build ROS Deb
run-name: ${{ github.actor }} is testing out building Debs from ROS package 🚀
on:
  push:
    branches:
      - master
jobs:
  build-ros-deb:
    runs-on: ubuntu-22.04

    steps:
      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Build ROS Deb
        uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          REPOS_FILE: https://raw.githubusercontent.com/MaxZubrytskyi/keyboard_teleop/master/sources.repos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true

      - shell: bash
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          ls -la; 
          curl -v -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" -H "Content-Type: multipart/form-data" --data-binary "@.some.deb" "http://95.216.32.240:5514/repository/keyboard_teleop/";